apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    environment: staging
    app: attribution-analytics
    tier: pre-production
    version: 1.0.0
    managed-by: kubernetes
    part-of: attribution-platform
  annotations:
    environment: staging
    description: "Staging namespace for Attribution Analytics Tool"
    owner: qa-team
    compliance: SOC2,GDPR,CCPA
    backup-policy: enabled
    monitoring: enhanced
    security.kubernetes.io/enforce-pod-security: restricted
    network-policy: enabled
    istio-injection: enabled
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  finalizers:
    - kubernetes

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"
    requests.memory: 16Gi
    limits.memory: 32Gi
    pods: "50"
    services: "25"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "25"
    requests.storage: 500Gi
    limits.storage: 1Ti

---
apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
  namespace: staging
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
  - type: PersistentVolumeClaim
    max:
      storage: 100Gi
    min:
      storage: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging-default-deny
  namespace: staging
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: staging
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: staging
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP