# Kubernetes ServiceAccounts for Multi-Touch Attribution Analytics System
# Version: v1.26+
# Purpose: Define service identities with secure authentication and authorization

---
# Backend Service Account
# Used by attribution backend services for secure pod authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: attribution-backend
  namespace: attribution
  labels:
    app: attribution-backend
    security-tier: backend
    environment: production
  annotations:
    kubernetes.io/description: "Service account for attribution backend services with restricted permissions"
    security.kubernetes.io/enforce-mountable-secrets: "true"
    security.kubernetes.io/enforce-namespace-isolation: "true"
automountServiceAccountToken: false  # Disable automatic token mounting for enhanced security

---
# Analytics Service Account
# Used by attribution analytics services for data processing
apiVersion: v1
kind: ServiceAccount
metadata:
  name: attribution-analytics
  namespace: attribution
  labels:
    app: attribution-analytics
    security-tier: analytics
    environment: production
  annotations:
    kubernetes.io/description: "Service account for attribution analytics services with data access controls"
    security.kubernetes.io/enforce-mountable-secrets: "true"
    security.kubernetes.io/enforce-namespace-isolation: "true"
automountServiceAccountToken: false  # Disable automatic token mounting for enhanced security

---
# Monitoring Service Account
# Used by monitoring and observability components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: monitoring
  labels:
    app: monitoring
    security-tier: observability
    environment: production
  annotations:
    kubernetes.io/description: "Service account for monitoring and observability components with restricted permissions"
    security.kubernetes.io/enforce-mountable-secrets: "true"
    security.kubernetes.io/enforce-namespace-isolation: "true"
automountServiceAccountToken: false  # Disable automatic token mounting for enhanced security