apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: attribution-backend-hpa
  namespace: attribution
  labels:
    app: attribution-backend
    component: api
    environment: production
spec:
  # Target the backend deployment for scaling
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attribution-backend
  
  # Maintain between 3-10 replicas to ensure high availability
  # and handle up to 10M+ events/day
  minReplicas: 3
  maxReplicas: 10
  
  # Define resource metrics for scaling decisions
  metrics:
    # Scale based on CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
    # Scale based on memory utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  
  # Configure scaling behavior for stability
  behavior:
    # Aggressive scale up to handle traffic spikes
    scaleUp:
      stabilizationWindowSeconds: 60  # Wait 60s before scaling up again
      policies:
        - type: Pods
          value: 2  # Add up to 2 pods at a time
          periodSeconds: 60
    
    # Conservative scale down to prevent thrashing
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5m before scaling down
      policies:
        - type: Pods
          value: 1  # Remove 1 pod at a time
          periodSeconds: 120  # Every 2m