apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: attribution-analytics
  labels:
    app: attribution-analytics
    component: backend
    environment: production
  annotations:
    kubernetes.io/created-by: infrastructure-team
    secret.kubernetes.io/auto-rotation: enabled
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # Database Credentials
  POSTGRES_USERNAME: cG9zdGdyZXNfdXNlcg== # postgres_user
  POSTGRES_PASSWORD: UGFzc3dvcmQxMjMh # Password123!
  POSTGRES_SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  POSTGRES_SSL_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  
  CLICKHOUSE_USERNAME: Y2xpY2tob3VzZV91c2Vy
  CLICKHOUSE_PASSWORD: Q2xpY2tIb3VzZVBhc3MxMjMh
  CLICKHOUSE_SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  CLICKHOUSE_SSL_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  
  REDIS_PASSWORD: UmVkaXNQYXNzMTIzIQ==
  REDIS_SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  
  # Authentication Secrets
  JWT_SECRET: and0X3NlY3JldF9rZXlfMTIz
  JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0=
  JWT_ALGORITHM: UlMyNTY=
  
  OAUTH_CLIENT_ID: b2F1dGhfY2xpZW50X2lk
  OAUTH_CLIENT_SECRET: b2F1dGhfY2xpZW50X3NlY3JldA==
  OAUTH_REDIRECT_URI: aHR0cHM6Ly9hcHAuYXR0cmlidXRpb24tYW5hbHl0aWNzLmNvbS9vYXV0aC9jYWxsYmFjaw==
  
  MFA_ISSUER: YXR0cmlidXRpb24tYW5hbHl0aWNz
  MFA_SECRET_KEY: bWZhX3NlY3JldF9rZXlfMTIz
  
  # Encryption Keys
  KMS_KEY_ID: YXJuOmF3czprbXM6cmVnaW9uOmtleS1pZA==
  KMS_REGION: dXMtd2VzdC0y
  
  AES_KEY: YWVzXzI1Nl9nY21fa2V5
  AES_IV: YWVzXzI1Nl9nY21faXY=
  
  HMAC_KEY: aG1hY19zaGEyNTZfa2V5
  HMAC_ALGORITHM: U0hBLTI1Ng==
  
  # Kafka Configuration
  KAFKA_USERNAME: a2Fma2FfdXNlcg==
  KAFKA_PASSWORD: a2Fma2FfcGFzc3dvcmQ=
  KAFKA_KEYSTORE: LS0tLS1CRUdJTiBLRVlTVE9SRS0tLS0t
  KAFKA_TRUSTSTORE: LS0tLS1CRUdJTiBUUlVTVFNUT1JFLS0tLS0=
  KAFKA_KEYSTORE_PASSWORD: a2V5c3RvcmVfcGFzc3dvcmQ=
  KAFKA_TRUSTSTORE_PASSWORD: dHJ1c3RzdG9yZV9wYXNzd29yZA==
  KAFKA_PROTOCOL: VExTdjEuMw==
  
  # TLS Configuration
  TLS_CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  TLS_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  TLS_CA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  TLS_VERSION: VExTdjEuMw==
  TLS_CIPHER_SUITES: VEFMX0FFU18yNTZfR0NNX1NIQTM4NA==
  
  # Monitoring Configuration
  MONITORING_API_KEY: bW9uaXRvcmluZ19hcGlfa2V5
  MONITORING_ENDPOINT: aHR0cHM6Ly9tb25pdG9yaW5nLmF0dHJpYnV0aW9uLWFuYWx5dGljcy5jb20=