apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
    component: monitoring
    version: 9.5.3
data:
  grafana.ini: |
    # Server Configuration
    [server]
    http_port = 3000
    domain = grafana.attribution-analytics.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    serve_from_sub_path = true
    protocol = https
    cert_file = /etc/grafana/certs/tls.crt
    cert_key = /etc/grafana/certs/tls.key
    
    # Security Configuration
    [security]
    admin_user = ${GRAFANA_ADMIN_USER}
    admin_password = ${GRAFANA_ADMIN_PASSWORD}
    secret_key = ${GRAFANA_SECRET_KEY}
    disable_gravatar = true
    cookie_secure = true
    strict_transport_security = true
    content_security_policy = true
    x_content_type_options = true
    x_xss_protection = true
    
    # Authentication Configuration
    [auth]
    disable_login_form = false
    oauth_auto_login = false
    login_maximum_inactive_lifetime_duration = 7d
    login_maximum_lifetime_duration = 30d
    disable_signout_menu = false
    signout_redirect_url = /login
    
    # Database Configuration
    [database]
    type = sqlite3
    path = grafana.db
    
    # Session Configuration
    [session]
    provider = redis
    provider_config = addr=redis:6379,db=0,pool_size=100,prefix=grafana:
    cookie_name = grafana_session
    session_life_time = 86400
    gc_interval_time = 86400
    
    # Dashboards Configuration
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/attribution.json
    min_refresh_interval = 5s
    versions_to_keep = 20
    
    # Users Configuration
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Editor
    default_theme = dark
    
    # Analytics Configuration
    [analytics]
    reporting_enabled = false
    check_for_updates = true
    
    # Metrics Configuration
    [metrics]
    enabled = true
    basic_auth_username = ${GRAFANA_METRICS_USER}
    basic_auth_password = ${GRAFANA_METRICS_PASSWORD}
    
    # Alerting Configuration
    [alerting]
    enabled = true
    execute_alerts = true
    evaluation_timeout_seconds = 30
    notification_timeout_seconds = 30
    max_attempts = 3
    
    # Unified Alerting Configuration
    [unified_alerting]
    enabled = true
    
    # Log Configuration
    [log]
    mode = console file
    level = info
    
    # External Image Storage
    [external_image_storage]
    provider = local
    
    # Rendering Configuration
    [rendering]
    server_url = http://renderer:8081/render
    callback_url = http://grafana:3000/
    
    # Datasources Configuration
    [datasources]
    datasource_limit = 5000

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server:9090
        isDefault: true
        version: 1
        editable: false
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
          httpMethod: "POST"
          manageAlerts: true
        secureJsonData:
          httpHeaderValue1: "Bearer ${PROMETHEUS_API_TOKEN}"

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Attribution Analytics'
        orgId: 1
        folder: 'Attribution'
        folderUid: 'attribution'
        type: file
        disableDeletion: true
        editable: false
        updateIntervalSeconds: 30
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true